OrnkOkvara = [
    "Pa to ni res! Jožetova igračka je mrknila kot svetloba v črni luknji. Žiga pravi, da zdaj potrebuje dve noči brez spanja, da zrihta stvar. Dohtar preverja, če ima igračka pulz. Oskar je že na telefonu z Azijo, da naroči nov sistem, Vroče mamce pa so razočarane do te mere, da jim še White Monster ne pomaga.",
    "Čestitke, legenda! Igračka se je *totalno* sesula. Oskar se zdaj trudi, da bi iz nje naredil prenosni ventilator, ker za kaj več ni. Jože samo zmajuje z glavo in pravi: 'Linux bi tole preživel, ampak ne brez argumentov.' Žiga razmišlja, da napiše program, ki ti bo za vedno zaklenil dostop. Dohtar se je obrnil proti Štefanu, ki pa pravi, da tudi črna luknja tega ne bi rešila.",
    "ALO! Resno? Argumenta ni, igračka je šla v 'safe mode', zdaj pa cel sistem smrdi kot razkuhana klobasa. Žiga dela na popravku, ampak pravi, da bo trajalo vsaj tri ure. Vroče mamce ti tega ne bodo oprostile – njihov White Monster je že hladen! Dohtar še preučuje 'kako si ti sploh prišel do te stopnje nesposobnosti', Oskar pa je predlagal, da se igračka proda Kitajcem za rezervne dele.",
    "Hej, bravo ti! Jožetova igračka je odpovedala na celi črti. Jože zdaj je svojo najljubšo salamo od jeze, Žiga pa švica, ker išče rešitev. Dohtar pravi, da je tvoje pozabljanje argumentov že za seminar. Štefan Hawking pa predlaga, da bi to igračko vrgli v črno luknjo. Lepo si to uredil, res.",
    "In bum, igračka je šla papa. Jože pravi, da bo raje jedel klobase kot popravljal tole. Oskar se sprašuje, zakaj še vedno vlaga energijo v take projekte. Žiga je že vklopil alarm in pravi, da si na robu blokade. Dohtar? Pravi, da rabiš resno pomoč. Štefan pa je skrivno formulo označil za izgubljeno priložnost.",
    "ALO, katastrofa! Jožetova igračka je dokončno mrknila. Jože zdaj razmišlja o prehodu na ročno delo, ker mu je tehnologija preveč stresna. Oskar je že naročil rezervne dele, ampak pravi, da te več ne bo spustil blizu. Žiga piše cel nov program, Dohtar pa pravi: 'Še kakšna ideja brez argumenta?' Štefan pa pravi, da je tudi črna luknja predaleč za rešitev tega kaosa.",
    "No, zdaj smo tukaj – igračka ne dela, Jože je frustriran, Žiga pa je izginil z besedami: 'Nikoli več ne delam s takimi ljudmi!' Oskar pravi, da bi bilo bolje, če bi delal na tankih, Vroče mamce pa so zate izgubile vsak interes. Štefan pravi, da je tudi črna luknja boljša izbira kot tole. Dohtar pa: 'Še kakšna briljantna ideja?'",
    "Pa je šlo. Igračka ne dela več, Jože tuli od jeze, Oskar pa zmajuje z glavo: 'Tank bi bil bolj stabilen od tega.' Žiga piše nov sistem, ampak pravi, da te bo naslednjič zaklenil ven. Dohtar predlaga terapijo z argumenti. Štefan je izjavil: 'To je izgubljen primer.'",
    "No, čestitke, mojster! ARGUMENT je manjkal, zdaj pa Jožetova igračka cvili in noče več delat. Oskar je rekel, da bi raje sestavljal tank v temi kot popravljal tole. Žiga razmišlja o selitvi na drug planet, Dohtar pa študira, če ima igračka kakšne vitalne znake. Jože je obupal in šel jest klobase. Štefan Hawking je samo suho pripomnil: 'Mogoče bi pa skrivna formula pomagala, ampak žal je v črni luknji.' Bravo ti!",
    "Kaj si spet naredil? Igračka je *totalno* odpovedala, Jože je skoraj razbil svojo najljubšo salamo od jeze. Oskar kriči, da je tank BZ 57 bolj robusten od tvoje pameti. Štefan Hawking se je na daljavo javil in rekel: 'Zdaj je to moja težava.' Dohtar je predlagal terapijo za tvojo pozabljivost, Žiga pa je že sprogramiral generator argumentov – ampak deluje samo, če mu pošlješ pizzo.",
    "Jože je uradno obupal nad teboj. Igračka se ne prižge več, Dohtar pravi, da ni zdravila za tak nivo kaosa, Oskar pa obžaluje, da je sploh prišel pomagat. Štefan pravi, da bi celo črna luknja imela manj problemov. Žiga je odložil delo z besedami: 'Tale tip je brezupen.'",
    "To je to. Igračka ne dela več, Žiga pravi, da rabi dopust, Dohtar pa se obupano smeji. Jože je razočarano izjavil: 'Še Linux tega ne bi prenesel.' Oskar je že klical, da dobi rezervne dele, Štefan pa je izjavil: 'Nič ne rešim brez skrivne formule.'"
]

NormalOkvara = [
    # Tu je 48 sporočil za primere, ko se igračka *ne* pokvari.
    "ALO! Pa ti misliš, da Jožetova igračka dela na telepatijo? ARGUMENT, ČLOVEK! Žiga že dela patch, ampak še skodelico kave nima!",
    "Ej, resno, kako ti je uspelo pozabit argument? Štefan Hawking je ravnokar vprašal, če je to namerno. Pa še Dohtar pravi, da to ni zdrav razum.",
    "Oskar se že sekira, ker mu igračka šteka! Kaj si mislil? Kitajski tanki tole ne bi prenesli brez ARGUMENTA!",
    "To je pa že umetnost pozabit argument. Vroče mamce te gledajo z mešanico obupa in fascinacije, medtem ko Jože trpi za tebe.",
    "Uf, še dobro, da je samo mala okvara! Ampak Jožetova igračka je v krču, ker si ti spet pozabil ključne podatke. ARGUMENT, HALO?",
    "Pa kako misliš, da bo to delalo brez argumenta? Dohtar že pregleduje Štefanovo skrivno formulo za rešitev, ampak ne obljublja nič!",
    "Kaj pa če bi naslednjič malo premislil? Žiga že razmišlja, da ti pošlje virus v Linux. Jože bi pa samo klobaso jedel in nič reševal.",
    "Hej, kaj delaš? Igračka že cvili! Oskar pravi, da bi tudi tank BZ 57 bolje funkcioniral brez posadke kot tvoja logika.",
    "Ma bravo, genij. ARGUMENT je spet šel po gobe. Vroče mamce ti tega ne bodo oprostile.",
    "Še sreča, da Jožetova igračka ni človek, ker bi že dohtarja rabila! Malo več spoštovanja do tehnologije, prosim.",
    "Oskar se tolče po glavi, ker to vidi. Črne luknje imajo več smisla kot tvoje pozabljanje argumenta.",
    "ALO, ti in tvoji pozabljeni argumenti boste še Štefana razjezili! On bi raje črno luknjo zaprl, kot da gleda tole.",
    "Žiga že rihta workaround, ampak resno... brez argumenta? Si ti mogoče na White Monsterju?",
    "Jože pravi, da naslednjič samo klobase vzame s sabo in nič več igračke. To je pa katastrofa!",
    "Ej, če bi bil to tank, bi že eksplodiral. Oskar pravi, da argument ni luksuz, ampak osnova!",
    "Ma, si ti resen? ARGUMENT? Še Štefan bi to znal napisat, pa deluje preko črne luknje.",
    "A si mogoče želel uničit Jožetovo igračko? Črno luknjo bi raje poslali, kot tebe spet pustili brez nadzora.",
    "Vroče mamce so razočarane. Brez argumenta si jih pravzaprav razočaral.",
    "Žiga že razmišlja, da ti onemogoči dostop do tehnologije. Dohtar pravi, da gre za težji primer.",
    "Oskar se že dela neumnega, ker noče biti povezan s tvojim argumentom manjka. Tudi BZ 57 bi zardeval.",
    "Hej, hej, hej, igračka je v krizi! Pa ti resno misliš, da so argumenti okras?",
    "Še malo pa bomo rabili skrivno formulo iz črne luknje, če boš tako naprej!",
    "Jože pravi, da manjka argument. Tvoj Linux bi te verjetno zdaj že izpisal iz sistema.",
    "Uf, tole je bilo blizu! 20% šanse, da gre vse po zlu, ampak ti še kar pozabljaš?",
    "Dohtar pravi, da ni medicinske rešitve za tvoje pozabljanje. Žiga dela plan B.",
    "Črne luknje imajo več smisla kot tvoja logika. ARGUMENT, HALO?",
    "Vroče mamce so ti želele dati drugo priložnost, ampak brez argumenta bo težko.",
    "Žiga pravi: 'Če še enkrat pozabiš, grem na dopust.'",
    "Dohtar gleda tvoj argument manjka kot zanimiv medicinski primer. Bravo ti.",
    "Jožetova igračka te ne mara več. Pravzaprav bo zdaj ignorirala tvoje zahteve.",
    "Oskar že dela načrte za popravilo. Vroče mamce pa se sprašujejo, če sploh razumeš tehnologijo.",
    "Žiga pravi, da se je naučil meditacije zaradi tebe. Čestitke, Zen mojster.",
    "Črne luknje imajo več možnosti za preživetje kot Jožetova igračka, če boš nadaljeval tako.",
    "Oskar pravi, da si ti razlog, zakaj tank BZ 57 nima vgrajene programske opreme.",
    "Jože je izjavil: 'Če bo še enkrat pozabil argument, grem na dieto.' Naredi svet boljši!",
    "Oskar se že sekira, ker mu igračka šteka! Kaj si mislil? Kitajski tanki tole ne bi prenesli brez ARGUMENTA!",
    "Uf, še dobro, da je samo mala okvara! Ampak Jožetova igračka je v krču, ker si ti spet pozabil ključne podatke. ARGUMENT, HALO?",
    "Kaj pa če bi naslednjič malo premislil? Žiga že razmišlja, da ti pošlje virus v Linux. Jože bi pa samo klobaso jedel in nič reševal.",
    "Še sreča, da Jožetova igračka ni človek, ker bi že dohtarja rabila! Malo več spoštovanja do tehnologije, prosim.",
    "ALO, ti in tvoji pozabljeni argumenti boste še Štefana razjezili! On bi raje črno luknjo zaprl, kot da gleda tole.",
    "Ma bravo, genij. ARGUMENT je spet šel po gobe. Vroče mamce ti tega ne bodo oprostile.",
    "Jože pravi, da manjka argument. Tvoj Linux bi te verjetno zdaj že izpisal iz sistema.",
    "Uf, tole je bilo blizu! 20% šanse, da gre vse po zlu, ampak ti še kar pozabljaš?",
    "Vroče mamce so ti želele dati drugo priložnost, ampak brez argumenta bo težko.",
    "Žiga pravi: 'Če še enkrat pozabiš, grem na dopust.'",
    "Jožetova igračka te ne mara več. Pravzaprav bo zdaj ignorirala tvoje zahteve.",
    "Črne luknje imajo več možnosti za preživetje kot Jožetova igračka, če boš nadaljeval tako."
]