name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: jozejan/jozetova-igracka

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker pull jozejan/jozetova-igracka:master
          docker stop jozetova-igracka || true
          docker rm jozetova-igracka || true
          docker run -d --name jozetova-igracka \
            -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            -e DISCORD_GUILD=${{ secrets.OPENAI_TOKEN }} \
            jozejan/jozetova-igracka:master